basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a simple songs library server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Songs Library
  version: "1.0"
paths:
  /deletesong:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Track ID
        in: body
        name: id
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: Delete song from lib
      tags:
      - song
  /getlib:
    get:
      consumes:
      - application/json
      parameters:
      - description: Song Name
        in: body
        name: songname
        required: true
        schema:
          type: string
      - description: Group
        in: body
        name: group
        required: true
        schema:
          type: string
      - description: Release Date
        in: body
        name: releasedate
        required: true
        schema:
          type: string
      - description: Link
        in: body
        name: link
        required: true
        schema:
          type: string
      - description: Offset
        in: body
        name: offset
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get song from lib
      tags:
      - song
  /getsong:
    get:
      consumes:
      - application/json
      parameters:
      - description: Song Name
        in: body
        name: songname
        required: true
        schema:
          type: string
      - description: Offset
        in: body
        name: offset
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get song from lib
      tags:
      - song
  /setsong:
    post:
      consumes:
      - application/json
      parameters:
      - description: Song Name
        in: body
        name: song
        required: true
        schema:
          type: string
      - description: Group
        in: body
        name: group
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Set song in lib
      tags:
      - song
  /updatesonginfo:
    patch:
      consumes:
      - application/json
      parameters:
      - description: Track ID
        in: body
        name: id
        required: true
        schema:
          type: integer
      - description: Song Name
        in: body
        name: songname
        schema:
          type: string
      - description: Group
        in: body
        name: group
        schema:
          type: string
      - description: Release Date
        in: body
        name: releasedate
        schema:
          type: string
      - description: Link
        in: body
        name: link
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: Update song info from lib
      tags:
      - song
  /updatesongtext:
    patch:
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
swagger: "2.0"
